runtime: custom
env: flex

# Remove the following line if this is the first App Engine service in
# your GCP account.
service: default
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10